pymc3 3.8 (Apache-2.0) has 1 incompatibilities in [tree_created]:
pymc3 
  h5py 2.10.0 [pymc3 (>=2.7.0)]
  tqdm 4.39.0 [pymc3 (>=4.8.4)]
  patsy 0.5.1 [pymc3 (>=0.4.0)]
    numpy 1.17.4 [pymc3 (>=1.13.0)] [patsy (>=1.4)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [cftime ()]
    six 1.12.0 [patsy ()] [python-dateutil (>=1.5)]
  pandas 0.25.3 [pymc3 (>=0.18.0)] [arviz (>=0.23)] [xarray (>=0.24)]
    numpy 1.17.4 [pymc3 (>=1.13.0)] [patsy (>=1.4)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [cftime ()]
    pytz 2019.1 [pandas (>=2017.2)]
    python-dateutil 2.8.1 [pandas (>=2.6.1)]
  scipy 1.3.3 [pymc3 (>=0.18.1)] [arviz (>=0.19)]
    numpy 1.17.4 [pymc3 (>=1.13.0)] [patsy (>=1.4)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [cftime ()]
  numpy 1.17.4 [pymc3 (>=1.13.0)] [patsy (>=1.4)] [pandas (>=1.13.3)] [scipy (>=1.13.3)] [arviz (>=1.12)] [netcdf4 (>=1.7)] [xarray (>=1.14)] [cftime ()]
  theano 1.0.4 [pymc3 (>=1.0.4)]
  arviz 0.5.1 [pymc3 (>=0.4.1)]
    netcdf4 1.5.3 [arviz ()]
      cftime 1.0.4.2 (INCOMPATIBLE! HAS GPL-3.0-only) [netcdf4 ()]
    xarray 0.14.1 [arviz (>=0.11)]
    matplotlib 3.1.2 [arviz (>=3.0)]
